name: qt-jack-test
base: core18
version: git
summary: qt-jack-test
description: |
  Let's try to snap a Qt5 jack client.

grade: devel
confinement: strict

apps:
  qt-jack-test:
    command: desktop-launch $SNAP/opt/qt-jack-test/bin/qt-jack-test
    plugs:
      - x11
      - opengl
      - home

parts:
  qt-jack-test:
    plugin: qmake
    source: .
    build-packages:
      - g++
    after:
      - desktop-qt5

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
